import React, { useMemo, useState } from "react";
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, MapPin, MoreHorizontal, Plus, Sparkles, UserRound } from "lucide-react";

const Schedule = () => {
  const [selected, setSelected] = useState(8);
  const [available, setAvailable] = useState(true);
  const days = useMemo(() => Array.from({ length: 7 }, (_, i) => 5 + i), []);
  const jobs = [
    { time: "10:30 AM", title: "Plumbing Repair", customer: "Rahul Sharma", place: "Delhi", status: "Confirmed" },
    { time: "1:30 PM", title: "AC Service", customer: "Amit Kumar", place: "Delhi", status: "Confirmed" },
    { time: "4:00 PM", title: "Electrical Work", customer: "Priya Singh", place: "Noida", status: "Pending" },
  ];

  return (
    <div className="min-h-screen bg-[#F7F8F7] px-4 py-6 sm:px-6 lg:px-8 dark:bg-slate-950">
      <div className="mx-auto max-w-7xl">
        <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-[#0E6B5C]">Smart planning</p><h1 className="mt-1 text-3xl font-black text-[#16302B] dark:text-white sm:text-4xl">My Schedule</h1><p className="mt-2 text-sm text-slate-500">Plan your jobs and keep your day balanced.</p></div><button onClick={() => setAvailable((v) => !v)} className="flex w-fit items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-slate-800 dark:bg-slate-900 dark:text-white"><span className={`h-2.5 w-2.5 rounded-full ${available ? "bg-[#0E6B5C]" : "bg-slate-400"}`} />{available ? "Accepting jobs" : "Paused"}</button></div>

        <div className="mb-6 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-5"><div className="flex items-center justify-between"><button className="rounded-xl p-2 hover:bg-slate-100 dark:hover:bg-slate-800"><ChevronLeft size={18} /></button><div className="text-center"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">October 2026</p><p className="mt-1 text-sm font-black text-slate-900 dark:text-white">Choose a work day</p></div><button className="rounded-xl p-2 hover:bg-slate-100 dark:hover:bg-slate-800"><ChevronRight size={18} /></button></div><div className="mt-5 grid grid-cols-7 gap-2">{days.map((day) => <button key={day} onClick={() => setSelected(day)} className={`rounded-2xl p-3 text-center transition duration-200 hover:-translate-y-1 ${selected === day ? "bg-[#16302B] text-white shadow-lg" : "bg-slate-50 text-slate-600 hover:bg-slate-100 dark:bg-slate-800 dark:text-slate-300"}`}><span className="block text-[10px] font-bold uppercase text-current/60">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][day % 7]}</span><span className="mt-1 block text-lg font-black">{day}</span>{day === 8 && <span className="mx-auto mt-1 block h-1.5 w-1.5 rounded-full bg-[#E08A3C]" />}</button>)}</div></div>

        <div className="grid gap-6 lg:grid-cols-[1.4fr_0.8fr]">
          <section className="rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-800"><div><h2 className="font-black text-[#16302B] dark:text-white">Today’s Timeline</h2><p className="mt-1 text-xs text-slate-500">3 scheduled jobs</p></div><button className="flex items-center gap-2 rounded-xl bg-[#16302B] px-3.5 py-2 text-xs font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#0E6B5C]"><Plus size={14} />Add slot</button></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{jobs.map((job) => <div key={job.time} className="group flex gap-4 p-5 transition hover:bg-slate-50 dark:hover:bg-slate-950"><div className="w-20 shrink-0"><p className="text-xs font-black text-[#16302B] dark:text-white">{job.time}</p><span className="mt-1 block text-[10px] text-slate-400">60 min</span></div><div className="relative flex flex-1 gap-3"><span className="mt-1 h-3 w-3 shrink-0 rounded-full bg-[#0E6B5C] ring-4 ring-[#0E6B5C]/10" /><div><h3 className="font-bold text-slate-900 dark:text-white">{job.title}</h3><div className="mt-1 flex flex-wrap gap-3 text-xs text-slate-500"><span className="flex items-center gap-1"><UserRound size={12} />{job.customer}</span><span className="flex items-center gap-1"><MapPin size={12} />{job.place}</span></div><span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${job.status === "Confirmed" ? "bg-green-50 text-green-600" : "bg-yellow-50 text-yellow-700"}`}>{job.status}</span></div></div><button className="self-start rounded-lg p-1.5 text-slate-400 opacity-0 transition group-hover:opacity-100 hover:bg-slate-100 dark:hover:bg-slate-800"><MoreHorizontal size={17} /></button></div>)}</div></section>

          <aside className="space-y-6"><div className="rounded-3xl bg-[#16302B] p-6 text-white shadow-xl"><div className="flex items-center gap-2 text-xs font-bold text-white/60"><Sparkles size={14} />Workload insight</div><p className="mt-3 text-3xl font-black">78%</p><p className="mt-1 text-sm text-white/65">Your day is optimally booked.</p><div className="mt-5 h-2 rounded-full bg-white/10"><div className="h-full w-[78%] rounded-full bg-[#E08A3C]" /></div><p className="mt-4 text-xs leading-5 text-white/55">You still have one flexible slot. Keeping it open can help you accept urgent requests.</p></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><CalendarDays size={18} className="text-[#0E6B5C]" /><h2 className="font-black text-[#16302B] dark:text-white">Day summary</h2></div><div className="mt-5 space-y-4"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm text-slate-500"><Clock3 size={15} />Booked time</span><b className="text-sm text-slate-900 dark:text-white">3h 00m</b></div><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Expected earnings</span><b className="text-sm text-[#0E6B5C]">₹2,650</b></div><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Travel buffer</span><b className="text-sm text-slate-900 dark:text-white">45 min</b></div></div><div className="mt-6 rounded-2xl bg-[#0E6B5C]/5 p-4 text-xs leading-5 text-slate-600 dark:bg-[#0E6B5C]/10 dark:text-slate-300"><Check size={14} className="mb-1 text-[#0E6B5C]" />Smart tip: keep 15–20 minutes between nearby jobs for unexpected delays.</div></div></aside>
        </div>
        <div className="h-8 md:hidden" />
      </div>
    </div>
  );
};

export default Schedule;
